### ISSUE TITLE
Need to add ntfs-3g package

### ISSUE THREAD

**Issue by BrantleyHobbs** [ronivay/xen-orchestra-vm#1]
Image works just fine, except that file restores from Windows VM's fail because the NTFS driver isn't installed.

Once I added the ntfs-3g package, everything worked just fine.

For reference, see here: 
https://xcp-ng.org/forum/topic/5498/file-restores-from-windows-guest-backups

**Comment by ronivay** [comment]
Hi,

Thanks. This package isn't part of the official "from sources" installation documentation so never added to script either. Looks like the official XOA appliance has it though and is obviously a requirement to do any file restore from windows disks.

Commited the addition of ntfs-3g package to main repo: https://github.com/ronivay/XenOrchestraInstallerUpdater/commit/ca1c1052104c5ed7611d8eef463940c6c02f1ffb

This will be available in the VM image when it's built next time (weekly build).
